//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hadith.Crawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class HadithContent
    {
        public int ContentID { get; set; }
        public Nullable<int> HadithID { get; set; }
        public Nullable<int> ChapterNo { get; set; }
        public Nullable<int> PageNo { get; set; }
        public string Narated { get; set; }
        public string ContentEnglish { get; set; }
        public string ContentIndonesia { get; set; }
        public string ContentArabic { get; set; }
        public string Grade { get; set; }
        public string Reference { get; set; }
        public string SanadTop { get; set; }
        public string SanadBottom { get; set; }
    }
}
