//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hadith.Parser
{
    using System;
    using System.Collections.Generic;
    
    public partial class HadithChapter
    {
        public int ChapterID { get; set; }
        public Nullable<int> ChapterNo { get; set; }
        public string Title { get; set; }
        public string TitleArabic { get; set; }
        public string Intro { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<int> HadithID { get; set; }
        public string ChapterNoStr { get; set; }
    }
}
