//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hadith.Parser
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HadithDB2Entities : DbContext
    {
        public HadithDB2Entities()
            : base("name=HadithDB2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Crawled> Crawleds { get; set; }
        public DbSet<Hadith> Hadiths { get; set; }
        public DbSet<HadithChapter> HadithChapters { get; set; }
        public DbSet<HadithContent> HadithContents { get; set; }
        public DbSet<HadithIndex> HadithIndexes { get; set; }
        public DbSet<HadithPage> HadithPages { get; set; }
    }
}
